### ISSUE TITLE
Move to main Cuis repository?

### ISSUE THREAD

**Issue by mmontone** [nmingotti/Cuis-Smalltalk-RegEx#8]
Hello,

would it be alright to move this Regex package to the Cuis repository?

Regular expressions are common enough, and I would love to just be able to clone Cuis and do Feature require: 'Regex'

**Comment by nmingotti** [comment]
Hello Mariano, sorry i saw the message only now. For me it is not a problem to put into Cuis repository.
BTW. I just rolled back the package to a decent state, I made some experiments in past months and I see only now i was making a mess !

**Comment by mmontone** [comment]
Hi Nicola. No problem! Your package is easy to install now using a package
mánager i'm developing now anyway.

**Comment by nmingotti** [comment]
Good ! I am going to try your package manager as soon as i can ! 

I close the issue. Bye
